[versions]

agp = "8.13.0"
kotlin = "2.2.20"
ksp = "2.2.10-2.0.2"


compileSdk = "36"
minSdk = "29"
targetSdk = "36"


versionCode = "1"
versionName = "0.3.0"


coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
appcompat = "1.7.1"
startup = "1.2.0"


composeBom = "2025.10.00"
material = "1.13.0"


navigation = "2.9.5"
kotlinxSerializationJson = "1.9.0"


hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
koin = "4.0.1"


firebaseBom = "34.4.0"
googleServices = "4.4.4"


retrofit = "3.0.0"
okhttp = "5.2.1"
ktor = "3.0.2"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"


room = "2.8.2"
datastore = "1.1.7"
workManager = "2.10.0"


coil = "2.7.0"
palette = "1.0.0"
exifinterface = "1.3.7"


googleSignin = "21.4.0"
credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
googleid = "1.1.1"


composeIcons = "1.1.1"
browser = "1.9.0"
haze = "1.6.10"
composeMarkdown = "0.5.4"


kermit = "2.0.8"
timber = "5.0.1"


spotless = "8.0.0"
detekt = "1.23.8"


junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
mockk = "1.14.6"
turbine = "1.2.1"
robolectric = "4.16"


leakcanary = "2.14"
kotlinTest = "2.2.0"
runner = "1.7.0"
core = "1.7.0"
animationCore = "1.9.3"

[libraries]

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }


androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }


androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }


kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }


hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }
firebase-functions = { group = "com.google.firebase", name = "firebase-functions" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
datastore-proto = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }

work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
work-hilt = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltNavigationCompose" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltNavigationCompose" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
androidx-palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }

google-signin = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "googleSignin" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }

androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }


haze = { group = "dev.chrisbanes.haze", name = "haze", version.ref = "haze" }


compose-markdown = { group = "com.github.jeziellago", name = "compose-markdown", version.ref = "composeMarkdown" }

compose-icons-feather = { group = "br.com.devsrsouza.compose.icons", name = "feather", version.ref = "composeIcons" }
compose-icons-tabler = { group = "br.com.devsrsouza.compose.icons", name = "tabler-icons", version.ref = "composeIcons" }
compose-icons-font-awesome = { group = "br.com.devsrsouza.compose.icons", name = "font-awesome", version.ref = "composeIcons" }
compose-icons-simple = { group = "br.com.devsrsouza.compose.icons", name = "simple-icons", version.ref = "composeIcons" }
compose-icons-octicons = { group = "br.com.devsrsouza.compose.icons", name = "octicons", version.ref = "composeIcons" }


timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }


kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }


junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }


androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }


androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-compose-animation-core = { group = "androidx.compose.animation", name = "animation-core", version.ref = "animationCore" }

[bundles]

androidx-core = [
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",
    "androidx-activity-compose",
    "androidx-appcompat"
]

compose = [
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
    "androidx-material3",
    "androidx-compose-material-icons-extended",
    "androidx-ui-text-google-fonts"
]

material-design = [
    "androidx-material3",
    "material"
]


navigation = [
    "androidx-navigation-compose",
    "kotlinx-serialization-json"
]

lifecycle = [
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-lifecycle-runtime-compose"
]

coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android",
    "kotlinx-coroutines-play-services"
]

hilt = [
    "hilt-android",
    "hilt-navigation-compose"
]


firebase = [
    "firebase-auth",
    "firebase-firestore",
    "firebase-analytics",
    "firebase-messaging",
    "firebase-functions",
    "firebase-storage"
]

networking = [
    "retrofit",
    "retrofit-converter-kotlinx-serialization",
    "okhttp",
    "okhttp-logging-interceptor"
]

ktor = [
    "ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json"
]

database = [
    "room-runtime",
    "room-ktx"
]

data-storage = [
    "datastore-preferences",
    "room-runtime",
    "room-ktx"
]


image-loading = [
    "coil-compose",
    "coil-svg",
    "androidx-palette"
]


authentication = [
    "google-signin",
    "androidx-credentials",
    "androidx-credentials-play-services-auth",
    "googleid"
]



icons = [
    "compose-icons-feather",
    "compose-icons-tabler",
    "compose-icons-font-awesome",
    "compose-icons-simple",
    "compose-icons-octicons"
]

work = [
    "work-runtime-ktx",
    "work-hilt"
]


testing-unit = [
    "junit",
    "mockk",
    "kotlinx-coroutines-test",
    "turbine",
    "robolectric"
]

testing-android = [
    "androidx-junit",
    "androidx-espresso-core",
    "androidx-ui-test-junit4"
]

testing = [
    "junit",
    "mockk",
    "kotlinx-coroutines-test",
    "turbine",
    "robolectric",
    "androidx-junit",
    "androidx-espresso-core",
    "androidx-ui-test-junit4"
]


debug = [
    "androidx-ui-tooling",
    "androidx-ui-test-manifest",
    "leakcanary-android"
]

[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }


kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }


hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }


ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }


google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }


spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
